export const U899_IMAGES = {
  icon: {
    src: "/899uimages/icon.jpeg",
    width: 200,
    height: 200,
    alt: "899u Game official app icon with purple branding",
  },
  promoBanner: {
    src: "/899uimages/banner.jpeg",
    width: 738,
    height: 369,
    alt: "899u Game promotional banner showing download bonus and app features for Pakistan",
  },
  appScreen: {
    src: "/899uimages/app-screen.jpeg",
    width: 395,
    height: 776,
    alt: "899u Game app home screen with deposit button, hot games and wallet balance",
  },
  appScreenAlt: {
    src: "/899uimages/app-screen-2.jpeg",
    width: 446,
    height: 686,
    alt: "899u Game mobile interface showing game lobby and earning options on Android",
  },
  loginBanner: {
    src: "/899uimages/login-banner.jpeg",
    width: 297,
    height: 170,
    alt: "899u Game login banner with phone number and password fields",
  },
  loginScreen: {
    src: "/899uimages/login.png",
    width: 1084,
    height: 1896,
    alt: "899u Game registration and login screen with OTP verification on mobile",
  },
  gamesLobby: {
    src: "/899uimages/games.png",
    width: 1084,
    height: 1896,
    alt: "899u Game lobby showing slots, casino and arcade titles available to play",
  },
  allGames: {
    src: "/899uimages/all-games.png",
    width: 1084,
    height: 1896,
    alt: "899u Game full game library with Aviator, Teen Patti, Fortune Tiger and more",
  },
  offers: {
    src: "/899uimages/offers.png",
    width: 1084,
    height: 1896,
    alt: "899u Game bonuses and promotions page with welcome bonus and daily rewards",
  },
  screenshots: [
    {
      src: "/899uimages/app-screen.jpeg",
      width: 395,
      height: 776,
      alt: "899u Game home screen with wallet and hot games for Pakistan players",
      caption: "Home & Wallet",
    },
    {
      src: "/899uimages/games.png",
      width: 1084,
      height: 1896,
      alt: "899u Game slots and casino lobby with popular titles",
      caption: "Game Lobby",
    },
    {
      src: "/899uimages/offers.png",
      width: 1084,
      height: 1896,
      alt: "899u Game daily bonuses, cashback and welcome offers in PKR",
      caption: "Bonuses & Offers",
    },
    {
      src: "/899uimages/login.png",
      width: 1084,
      height: 1896,
      alt: "899u Game secure login and registration screen with OTP",
      caption: "Login & Register",
    },
  ],
} as const;
